// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/17/2026, 7:21:08 PM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["/Users/mac/Documents/spsn/member/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/spsn/member/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/spsn/member/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/spsn/member/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/spsn/member/plugins/**/*.{js,ts,mjs}","/Users/mac/Documents/spsn/member/composables/**/*.{js,ts,mjs}","/Users/mac/Documents/spsn/member/utils/**/*.{js,ts,mjs}","/Users/mac/Documents/spsn/member/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/spsn/member/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/spsn/member/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/mac/Documents/spsn/member/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;